### ISSUE TITLE
Anubis IDE not loading

### ISSUE THREAD

**Issue by ts4044** [AnubisLMS/IDE#17]
My IDE crashed while I was working on it, I then saw the message on the Dashboard about upgrades. Even after waiting for sometime, my IDE is not able to load. Tried on Firefox, Firefox Private and Chrome.
Here are the console logs from Firefox:
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. ide
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:42:9
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-solid-900.eot?#iefix (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-solid-900.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-solid-900.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-solid-900.ttf (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-solid-900.svg#fontawesome (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-regular-400.eot?#iefix (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-regular-400.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-regular-400.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-regular-400.ttf (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-regular-400.svg#fontawesome (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-brands-400.eot?#iefix (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-brands-400.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-brands-400.woff (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-brands-400.ttf (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://use.fontawesome.com/releases/v5.13.0/webfonts/fa-brands-400.svg#fontawesome (“font-src”).
Firefox can’t establish a connection to the server at wss://anubis-lms.io/ide/stable-129500ee4c8ab7263461ffe327268ba56b9f210d?reconnectionToken=61ee1183-b7f3-45b3-b525-0cda9def0c3e&reconnection=false&skipWebSocketFrames=false. browserSocketFactory.ts:79:17
  ERR [remote-connection][Management   ][61ee1…][initial][anubis-lms.io:443] socketFactory.connect() failed or timed out. Error: log.ts:313:11
  ERR CodeExpectedError: WebSocket close with status code 1006
    c errors.ts:245
    _ remoteAuthorityResolver.ts:86
    w browserSocketFactory.ts:165
log.ts:313:11
  ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error: log.ts:313:11
  ERR CodeExpectedError: WebSocket close with status code 1006
    c errors.ts:245
    _ remoteAuthorityResolver.ts:86
    w browserSocketFactory.ts:165
log.ts:313:11
Firefox can’t establish a connection to the server at wss://anubis-lms.io/ide/stable-129500ee4c8ab7263461ffe327268ba56b9f210d?reconnectionToken=af19c755-6118-424a-8e1a-4cab885a78b3&reconnection=false&skipWebSocketFrames=false. browserSocketFactory.ts:79:17
  ERR [remote-connection][Management   ][af19c…][initial][anubis-lms.io:443] socketFactory.connect() failed or timed out. Error: log.ts:313:11
  ERR CodeExpectedError: WebSocket close with status code 1006
    c errors.ts:245
    _ remoteAuthorityResolver.ts:86
    w browserSocketFactory.ts:165
log.ts:313:11
  ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error: log.ts:313:11
  ERR CodeExpectedError: WebSocket close with status code 1006
    c errors.ts:245
    _ remoteAuthorityResolver.ts:86
    w browserSocketFactory.ts:165
log.ts:313:11
Firefox can’t establish a connection to the server at wss://anubis-lms.io/ide/stable-129500ee4c8ab7263461ffe327268ba56b9f210d?reconnectionToken=c43e2dfc-243e-42af-8753-015778dd049a&reconnection=false&skipWebSocketFrames=false. browserSocketFactory.ts:79:17
  ERR [remote-connection][Management   ][c43e2…][initial][anubis-lms.io:443] socketFactory.connect() failed or timed out. Error: log.ts:313:11
  ERR CodeExpectedError: WebSocket close with status code 1006
    c errors.ts:245
    _ remoteAuthorityResolver.ts:86
    w browserSocketFactory.ts:165
    l dom.ts:46
    o dom.ts:67
    w browserSocketFactory.ts:151
    create browserSocketFactory.ts:203
    connect browserSocketFactory.ts:278
    c remoteAgentConnection.ts:195
    r remoteAgentConnection.ts:236
    n remoteAgentConnection.ts:323
    u remoteAgentConnection.ts:345
    C remoteAgentConnection.ts:421
    E remoteAgentConnection.ts:447
log.ts:313:11
  ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error: log.ts:313:11
  ERR CodeExpectedError: WebSocket close with status code 1006
    c errors.ts:245
    _ remoteAuthorityResolver.ts:86
    w browserSocketFactory.ts:165
    l dom.ts:46
    o dom.ts:67
    w browserSocketFactory.ts:151
    create browserSocketFactory.ts:203
    connect browserSocketFactory.ts:278
    c remoteAgentConnection.ts:195
    r remoteAgentConnection.ts:236
    n remoteAgentConnection.ts:323
    u remoteAgentConnection.ts:345
    C remoteAgentConnection.ts:421
    E remoteAgentConnection.ts:447
log.ts:313:11
```
After a minute, loads the page to this error :
![image](https://user-images.githubusercontent.com/90651906/202875409-df635dad-962f-4ba3-8b25-cadb526e0041.png)

**Comment by wabscale** [comment]
What platform is this on?

I looked into your IDE, and I believe the settings for your assignment (final for distsys) has the memory limits for IDEs set too low.

**Comment by ts4044** [comment]
Windows.
